DROP TABLE IF EXISTS TRADE;
CREATE TABLE TRADE (
    TRADE_ID VARCHAR(5) NOT NULL,
    VERSION INT(8) NOT NULL,
    COUNTER_PARTY VARCHAR(10) NOT NULL,
    BOOK_ID VARCHAR(10) NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    CREATED_DATE DATE NOT NULL,
    EXPIRED VARCHAR(1),
    PRIMARY KEY(TRADE_ID, VERSION)
);